spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:memDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .html
  security:
    user:
      name: root
      password: passwd
server:
  error:
    whitelabel:
      enabled: false
